version: "3.7"

services:
  alvtime-typescript-client:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - /workspace/node_modules/
    command: /bin/sh -c "while sleep 1000; do :; done"

  alvtime-web-api:
    image: docker.pkg.github.com/alv-no/alvtime-go-client/alvtime-web-api-no-auth:latest
    links:
      - alvtime-database
    environment:
      - ConnectionStrings__AlvTime_db=Data Source=tcp:alvtime-database,1433;Initial Catalog=AlvDevDB;User ID=sa;Password=AlvTimeTestErMoro32
    expose:
      - "80"
    ports:
      - "8000:80"

  alvtime-database:
    image: alvnoas/alvtime-database:latest
    expose:
      - "1433"
    ports:
      - "1433:1433"
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # So that the container doesn't shut down, sleep this thread
        sleep infinity
