# This is a basic workflow to help you get started with Actions

name: Publish Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    paths-ignore:
      - "package.json"
  pull_request:
    branches: [master]
    paths-ignore:
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@octocat"
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
