name: test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u Alvarbot --password-stdin

      - name: Set up environment
        run: docker-compose -f .devcontainer/docker-compose.yaml up -d && sleep 5

      - name: Run tests
        run: docker-compose -f .devcontainer/docker-compose.yaml run alvtime-typescript-client npm test
